### ISSUE TITLE
Support Open VSX

### ISSUE THREAD

**Issue by rdrpenguin04** [azdavis/ungrammar-tools#1]
Hello!

This plugin looks extremely useful. As a user of Code - OSS, it would be nice to have the extension available on the Open VSX registry so I wouldn't have to build from source.

Thank you for making this extension; let me know if there's any way I can help!

**Comment by azdavis** [comment]
Ok here you go: https://open-vsx.org/extension/azdavis/ungrammar

**Comment by rdrpenguin04** [comment]
Thank you! :smile:
